name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 22.14.0
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Publish core
        if: github.ref == 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/core
          rm -rf node_modules pnpm-lock.yaml && pnpm install
          pnpm build
          pnpm test
          npm publish

      - name: Publish vue
        if: github.ref == 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/vue
          rm -rf node_modules pnpm-lock.yaml && pnpm install
          pnpm build
          pnpm build
          npm publish

      - name: Build docs
        run: |
          cd apps/docs
          rm -rf node_modules pnpm-lock.yaml && pnpm install
          pnpm build
